theme = "nord"

[editor]
auto-format = false
shell = ["nu", "-c"]
text-width = 120

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.cursor-shape]
insert = "bar"


[keys.insert]
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"


[keys.normal]
# Create splits
C-h = ["vsplit", "jump_view_left"]
C-j = "hsplit"
C-k = ["hsplit", "jump_view_up"]
C-l = "vsplit"
# Navigate splits
H = "jump_view_left"
J = "jump_view_down"
K = "jump_view_up"
L = "jump_view_right"


[keys.normal."space"]
f = "no_op"
F = "no_op"
e = "file_picker_in_current_directory"
E = "file_picker"
k = "no_op"
a = "no_op"
"tab" = "buffer_picker"
h = "hover"
"ret" = "code_action"
"space" = "command_palette"
